//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mid
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ICDBTrdAEntities : DbContext
    {
        public ICDBTrdAEntities()
            : base("name=ICDBTrdAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityTypes> ActivityTypes { get; set; }
        public virtual DbSet<ActivSetup> ActivSetup { get; set; }
        public virtual DbSet<AgeBalance> AgeBalance { get; set; }
        public virtual DbSet<AstCompany> AstCompany { get; set; }
        public virtual DbSet<AstDprtmnt> AstDprtmnt { get; set; }
        public virtual DbSet<Astsupctg> Astsupctg { get; set; }
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<FixAsetsCat> FixAsetsCat { get; set; }
        public virtual DbSet<FixdAsetsLoc> FixdAsetsLoc { get; set; }
        public virtual DbSet<FixdAsetstype> FixdAsetstype { get; set; }
        public virtual DbSet<FixdAstSalDep> FixdAstSalDep { get; set; }
        public virtual DbSet<FixdAstStatus> FixdAstStatus { get; set; }
        public virtual DbSet<FixdDepStat> FixdDepStat { get; set; }
        public virtual DbSet<GLAnalytical1> GLAnalytical1 { get; set; }
        public virtual DbSet<GLAnalytical2> GLAnalytical2 { get; set; }
        public virtual DbSet<GLAstAcnBnk> GLAstAcnBnk { get; set; }
        public virtual DbSet<GLAstAcntyp> GLAstAcntyp { get; set; }
        public virtual DbSet<GLAstbank> GLAstbank { get; set; }
        public virtual DbSet<GLAstinvAdj> GLAstinvAdj { get; set; }
        public virtual DbSet<GLAstJrntyp> GLAstJrntyp { get; set; }
        public virtual DbSet<GLjrnal> GLjrnal { get; set; }
        public virtual DbSet<GLjrntrs> GLjrntrs { get; set; }
        public virtual DbSet<GlLast> GlLast { get; set; }
        public virtual DbSet<GLMonth> GLMonth { get; set; }
        public virtual DbSet<Glprvyer> Glprvyer { get; set; }
        public virtual DbSet<HrAstdeductntyp> HrAstdeductntyp { get; set; }
        public virtual DbSet<HrAstDeprtmnt> HrAstDeprtmnt { get; set; }
        public virtual DbSet<HrAstEmpstu> HrAstEmpstu { get; set; }
        public virtual DbSet<HrAstErngtyp> HrAstErngtyp { get; set; }
        public virtual DbSet<HrAstJobtbl> HrAstJobtbl { get; set; }
        public virtual DbSet<HrAstPymntype> HrAstPymntype { get; set; }
        public virtual DbSet<HrAstReljan> HrAstReljan { get; set; }
        public virtual DbSet<HrAstReqtyp> HrAstReqtyp { get; set; }
        public virtual DbSet<HrAststate> HrAststate { get; set; }
        public virtual DbSet<InvAstArea> InvAstArea { get; set; }
        public virtual DbSet<InvAstCardTyp> InvAstCardTyp { get; set; }
        public virtual DbSet<InvAstCity> InvAstCity { get; set; }
        public virtual DbSet<InvAstCntry> InvAstCntry { get; set; }
        public virtual DbSet<InvAstcPayType> InvAstcPayType { get; set; }
        public virtual DbSet<InvAstCurncy> InvAstCurncy { get; set; }
        public virtual DbSet<InvAstCustmcatg> InvAstCustmcatg { get; set; }
        public virtual DbSet<InvAstMarket> InvAstMarket { get; set; }
        public virtual DbSet<InvAstNutrbusn> InvAstNutrbusn { get; set; }
        public virtual DbSet<InvAstPymwys> InvAstPymwys { get; set; }
        public virtual DbSet<InvAstRefTyp> InvAstRefTyp { get; set; }
        public virtual DbSet<InvAstRefTypMain> InvAstRefTypMain { get; set; }
        public virtual DbSet<InvAstSalesman> InvAstSalesman { get; set; }
        public virtual DbSet<InvAstwrkPeriod> InvAstwrkPeriod { get; set; }
        public virtual DbSet<InvLimit_Qty> InvLimit_Qty { get; set; }
        public virtual DbSet<InvLoddtl> InvLoddtl { get; set; }
        public virtual DbSet<InvLodhdr> InvLodhdr { get; set; }
        public virtual DbSet<InvPoDtl> InvPoDtl { get; set; }
        public virtual DbSet<InvPoHdr> InvPoHdr { get; set; }
        public virtual DbSet<InvQutdtl> InvQutdtl { get; set; }
        public virtual DbSet<InvQuthdr> InvQuthdr { get; set; }
        public virtual DbSet<InvSalReqdtl> InvSalReqdtl { get; set; }
        public virtual DbSet<InvSalReqhdr> InvSalReqhdr { get; set; }
        public virtual DbSet<Lang_Controls> Lang_Controls { get; set; }
        public virtual DbSet<Lang_Forms> Lang_Forms { get; set; }
        public virtual DbSet<LCItemexp> LCItemexp { get; set; }
        public virtual DbSet<LcPymwys> LcPymwys { get; set; }
        public virtual DbSet<MainBranch> MainBranch { get; set; }
        public virtual DbSet<MainBranch2> MainBranch2 { get; set; }
        public virtual DbSet<MainBranchDlv> MainBranchDlv { get; set; }
        public virtual DbSet<MainBranchDlv2> MainBranchDlv2 { get; set; }
        public virtual DbSet<MainCmpnam> MainCmpnam { get; set; }
        public virtual DbSet<MtsChartAc> MtsChartAc { get; set; }
        public virtual DbSet<MtsClosAcnt> MtsClosAcnt { get; set; }
        public virtual DbSet<MtsCostcntr> MtsCostcntr { get; set; }
        public virtual DbSet<MtsCustmr> MtsCustmr { get; set; }
        public virtual DbSet<MtsCustmrOthr> MtsCustmrOthr { get; set; }
        public virtual DbSet<MtsEmpadmin> MtsEmpadmin { get; set; }
        public virtual DbSet<MtsEmpcntrct> MtsEmpcntrct { get; set; }
        public virtual DbSet<MtsFixdAsets> MtsFixdAsets { get; set; }
        public virtual DbSet<MtsItmcatgry> MtsItmcatgry { get; set; }
        public virtual DbSet<MtsItmfsunit> MtsItmfsunit { get; set; }
        public virtual DbSet<MtsItmLoction> MtsItmLoction { get; set; }
        public virtual DbSet<MtsItmMfs> MtsItmMfs { get; set; }
        public virtual DbSet<MtsItmOthr> MtsItmOthr { get; set; }
        public virtual DbSet<MtsItmunit> MtsItmunit { get; set; }
        public virtual DbSet<MtsLC> MtsLC { get; set; }
        public virtual DbSet<MtsSuplir> MtsSuplir { get; set; }
        public virtual DbSet<MtsSuplirOthr> MtsSuplirOthr { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sec_Controls> Sec_Controls { get; set; }
        public virtual DbSet<Sec_Forms> Sec_Forms { get; set; }
        public virtual DbSet<Sec_GrpMenuPrvldg> Sec_GrpMenuPrvldg { get; set; }
        public virtual DbSet<Sec_MainMenu> Sec_MainMenu { get; set; }
        public virtual DbSet<Sec_Roles> Sec_Roles { get; set; }
        public virtual DbSet<Sec_Users> Sec_Users { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<FixdDepDtl> FixdDepDtl { get; set; }
        public virtual DbSet<ItmsCatgry> ItmsCatgry { get; set; }
        public virtual DbSet<ItmsExpdt> ItmsExpdt { get; set; }
        public virtual DbSet<Itmskind> Itmskind { get; set; }
        public virtual DbSet<ItmsMfsunit> ItmsMfsunit { get; set; }
        public virtual DbSet<ItmsUnit> ItmsUnit { get; set; }
        public virtual DbSet<LCexpensDtl> LCexpensDtl { get; set; }
        public virtual DbSet<LCexpensHdr> LCexpensHdr { get; set; }
        public virtual DbSet<LcItmTrs> LcItmTrs { get; set; }
        public virtual DbSet<MSreplication_subscriptions> MSreplication_subscriptions { get; set; }
        public virtual DbSet<MSsubscription_agents> MSsubscription_agents { get; set; }
        public virtual DbSet<Sec_UsrMenuPrvldg> Sec_UsrMenuPrvldg { get; set; }
        public virtual DbSet<Adj> Adj { get; set; }
        public virtual DbSet<AllItemInGroup> AllItemInGroup { get; set; }
        public virtual DbSet<CountGroupInstore> CountGroupInstore { get; set; }
        public virtual DbSet<GroupinStore> GroupinStore { get; set; }
        public virtual DbSet<PaymentCert> PaymentCert { get; set; }
        public virtual DbSet<Stloddtlnutrbusn> Stloddtlnutrbusn { get; set; }
        public virtual DbSet<StsQry3> StsQry3 { get; set; }
        public virtual DbSet<Stsqry32> Stsqry32 { get; set; }
        public virtual DbSet<Uniterror> Uniterror { get; set; }
        public virtual DbSet<uniterror20> uniterror20 { get; set; }
        public virtual DbSet<VIEW1> VIEW1 { get; set; }
        public virtual DbSet<VIEW2> VIEW2 { get; set; }
        public virtual DbSet<VIEW3> VIEW3 { get; set; }
        public virtual DbSet<ViewRptCutmReq> ViewRptCutmReq { get; set; }
        public virtual DbSet<viewRptSalQut> viewRptSalQut { get; set; }
        public virtual DbSet<ViewStrqNavi> ViewStrqNavi { get; set; }
        public virtual DbSet<viewStSaldtlNavi> viewStSaldtlNavi { get; set; }
        public virtual DbSet<viwCurGroupcostStkitm> viwCurGroupcostStkitm { get; set; }
        public virtual DbSet<viwCurGroupStkitm> viwCurGroupStkitm { get; set; }
        public virtual DbSet<viwGroupStkitm> viwGroupStkitm { get; set; }
        public virtual DbSet<viwItmUnit> viwItmUnit { get; set; }
        public virtual DbSet<viwStkitm> viwStkitm { get; set; }
    
        public virtual ObjectResult<login_check_Result> login_check(string user_name, string password)
        {
            var user_nameParameter = user_name != null ?
                new ObjectParameter("user_name", user_name) :
                new ObjectParameter("user_name", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<login_check_Result>("login_check", user_nameParameter, passwordParameter);
        }
    
        public virtual int register(string user_name, string password, string email, Nullable<int> group_id)
        {
            var user_nameParameter = user_name != null ?
                new ObjectParameter("user_name", user_name) :
                new ObjectParameter("user_name", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var group_idParameter = group_id.HasValue ?
                new ObjectParameter("group_id", group_id) :
                new ObjectParameter("group_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("register", user_nameParameter, passwordParameter, emailParameter, group_idParameter);
        }
    
        public virtual ObjectResult<select_grid_Result> select_grid(Nullable<int> no, Nullable<int> month_no)
        {
            var noParameter = no.HasValue ?
                new ObjectParameter("no", no) :
                new ObjectParameter("no", typeof(int));
    
            var month_noParameter = month_no.HasValue ?
                new ObjectParameter("month_no", month_no) :
                new ObjectParameter("month_no", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_grid_Result>("select_grid", noParameter, month_noParameter);
        }
    
        public virtual ObjectResult<select_grid_costcntr_Result> select_grid_costcntr(Nullable<int> no, Nullable<int> month_no, Nullable<int> cmp_no)
        {
            var noParameter = no.HasValue ?
                new ObjectParameter("no", no) :
                new ObjectParameter("no", typeof(int));
    
            var month_noParameter = month_no.HasValue ?
                new ObjectParameter("month_no", month_no) :
                new ObjectParameter("month_no", typeof(int));
    
            var cmp_noParameter = cmp_no.HasValue ?
                new ObjectParameter("cmp_no", cmp_no) :
                new ObjectParameter("cmp_no", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_grid_costcntr_Result>("select_grid_costcntr", noParameter, month_noParameter, cmp_noParameter);
        }
    
        public virtual ObjectResult<select_grid_MtsCustmr_Result> select_grid_MtsCustmr(Nullable<int> no, Nullable<int> month_no, Nullable<int> cmp_no)
        {
            var noParameter = no.HasValue ?
                new ObjectParameter("no", no) :
                new ObjectParameter("no", typeof(int));
    
            var month_noParameter = month_no.HasValue ?
                new ObjectParameter("month_no", month_no) :
                new ObjectParameter("month_no", typeof(int));
    
            var cmp_noParameter = cmp_no.HasValue ?
                new ObjectParameter("cmp_no", cmp_no) :
                new ObjectParameter("cmp_no", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_grid_MtsCustmr_Result>("select_grid_MtsCustmr", noParameter, month_noParameter, cmp_noParameter);
        }
    
        public virtual ObjectResult<select_grid_mtssuplier_Result> select_grid_mtssuplier(Nullable<int> no, Nullable<int> month_no, Nullable<int> cmp_no)
        {
            var noParameter = no.HasValue ?
                new ObjectParameter("no", no) :
                new ObjectParameter("no", typeof(int));
    
            var month_noParameter = month_no.HasValue ?
                new ObjectParameter("month_no", month_no) :
                new ObjectParameter("month_no", typeof(int));
    
            var cmp_noParameter = cmp_no.HasValue ?
                new ObjectParameter("cmp_no", cmp_no) :
                new ObjectParameter("cmp_no", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_grid_mtssuplier_Result>("select_grid_mtssuplier", noParameter, month_noParameter, cmp_noParameter);
        }
    }
}
